- name: Installing Terraform, Packer, gopass, summon and gopass-summon provider
  hosts: localhost
  become: yes
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - gnupg
          - software-properties-common
          - curl
          - git
          - rng-tools
        state: latest

#    - name: Install Keyring for Hashicorp
#      command: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add Hashicorp repository to list of repositories
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        content: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com jammy main
        mode: "0644"

    - name: Get the gopass key into the keyring
      ansible.builtin.get_url:
        url: https://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg
        dest: "/usr/share/keyrings/gopass-archive-keyring.gpg"
        mode: "0644"

    - name: Add gopass repository to list of repositories
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/gopass.source
        content: deb [signed-by=/usr/share/keyrings/gopass-archive-keyring.gpg] https://packages.gopass.pw/repos/gopass stable main
        mode: "0644"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: latest

    - name: Install Packer
      ansible.builtin.apt:
        name: packer
        state: latest

    - name: Install gopass
      ansible.builtin.apt:
        pkg:
          - gopass
          - gopass-archive-keyring
        state: latest

    - name: install summon
      ansible.builtin.apt:
        deb: https://github.com/cyberark/summon/releases/download/v0.9.5/summon_0.9.5_amd64.deb


      

